https://big.oisd.nl|OISD|comprehensive
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt|GoodbyeAds|comprehensive
https://hosts.anudeep.me/mirror/adservers.txt|anudeepND|comprehensive
https://someonewhocares.org/hosts/zero/hosts|DanPollock|comprehensive
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0|PeterLowe|comprehensive
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt|WindowsSpyBlocker|comprehensive